<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
/**
 * This file is generated by Webpack, do not edit it directly.
 */
return [
	'handle' => 'elementor-v2-editor-design-system',
	'deps' => [
		'elementor-v2-editor',
		'elementor-v2-editor-app-bar',
		'elementor-v2-editor-canvas',
		'elementor-v2-editor-current-user',
		'elementor-v2-editor-default-styles',
		'elementor-v2-editor-documents',
		'elementor-v2-editor-global-classes',
		'elementor-v2-editor-notifications',
		'elementor-v2-editor-panels',
		'elementor-v2-editor-ui',
		'elementor-v2-editor-v1-adapters',
		'elementor-v2-editor-variables',
		'elementor-v2-events',
		'elementor-v2-http-client',
		'elementor-v2-icons',
		'elementor-v2-query',
		'elementor-v2-ui',
		'react',
		'wp-i18n',
	],
];
