<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
/**
 * This file is generated by Webpack, do not edit it directly.
 */
return [
	'handle' => 'elementor-v2-editor-embedded-documents-manager',
	'deps' => [
		'elementor-v2-editor-documents',
		'elementor-v2-editor-styles-repository',
		'elementor-v2-editor-v1-adapters',
	],
];
