<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
/**
 * This file is generated by Webpack, do not edit it directly.
 */
return [
	'handle' => 'elementor-v2-editor-agents',
	'deps' => [
		'elementor-v2-editor-documents',
		'elementor-v2-editor-site-settings',
		'elementor-v2-editor-v1-adapters',
		'elementor-v2-ui',
		'react',
		'wp-i18n',
	],
];
