<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
/**
 * This file is generated by Webpack, do not edit it directly.
 */
return [
	'handle' => 'elementor-v2-editor-audits',
	'deps' => [
		'elementor-v2-editor-app-bar',
		'elementor-v2-editor-elements',
		'elementor-v2-editor-floating-panels',
		'elementor-v2-editor-mcp',
		'elementor-v2-editor-notifications',
		'elementor-v2-editor-v1-adapters',
		'elementor-v2-events',
		'elementor-v2-http-client',
		'elementor-v2-icons',
		'elementor-v2-session',
		'elementor-v2-store',
		'elementor-v2-ui',
		'react',
		'wp-i18n',
	],
];
