on:
    push:
      branches: [test]
    workflow_dispatch:

name: Deploy website - TEST
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    environment: test
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: Transform wp-config.php
      run: |
        echo "Init transform: wp-config.php"
        sed -i 's/WP_DB_NAME/${{ secrets.WP_DB_NAME }}/g' ./app/wp-config.php
        sed -i 's/WP_DB_USER/${{ secrets.WP_DB_USER }}/g' ./app/wp-config.php
        sed -i 's/WP_DB_PASSWORD/${{ secrets.WP_DB_PASSWORD }}/g' ./app/wp-config.php
        sed -i 's/WP_DB_HOST/${{ secrets.WP_DB_HOST }}/g' ./app/wp-config.php
        sed -i 's/AWS_S3_ACCESS_KEY/${{ secrets.AWS_S3_ACCESS_KEY }}/g' ./app/wp-config.php
        sed -i 's/AWS_S3_SECRET_KEY/${{ secrets.AWS_S3_SECRET_KEY }}/g' ./app/wp-config.php
        sed -i 's/WP_S3_BUCKET/${{ secrets.WP_S3_BUCKET }}/g' ./app/wp-config.php
        echo "End transform: wp-config.php"

    - name: Deploy to Server - SSH
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SOURCE: "./app/"
        REMOTE_HOST: ${{ secrets.FTP_HOST }}
        REMOTE_PORT: 65002
        REMOTE_USER: ${{ secrets.FTP_USER }}
        TARGET: "/home/${{ secrets.FTP_USER }}/domains/test-f7p.internetdsa.com/public_html"
        EXCLUDE: "/dist/, /node_modules/"