on:
    push:
      branches: [test]
    workflow_dispatch:

name: Deploy website - TEST
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    environment: test
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    # - name: 📂 Sync files
    #   uses: SamKirkland/FTP-Deploy-Action@v4.3.5
    #   with:
    #     server: ${{ secrets.FTP_HOST }}
    #     username: ${{ secrets.FTP_USER }}
    #     password: ${{ secrets.FTP_PWD }}
    #     port: 65002
    #     local-dir: ./app/
    #     server-dir: /home/${{ secrets.FTP_USER }}/domains/test-f7p.internetdsa.com/public_html/
    #     protocol: ftps

    - name: 📂 Sync files SFTP
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        username: ${{ secrets.FTP_USER }}
        server: ${{ secrets.FTP_HOST }}
        port: 65002
        local_path: './app/*'
        remote_path: '/home/${{ secrets.FTP_USER }}/domains/test-f7p.internetdsa.com/public_html/'
        sftp_only: true
        password: ${{ secrets.FTP_PWD }}